# Generated by Django 3.0.4 on 2020-06-11 09:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalmLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
